# Generated by Django 2.1.7 on 2019-02-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IsWillingToRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestObject',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='iswillingtorent',
            name='testobject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.TestObject'),
        ),
        migrations.AddField(
            model_name='iswillingtorent',
            name='testuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.TestUser'),
        ),
    ]
