# Generated by Django 2.1.7 on 2019-04-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuffsharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
