# Generated by Django 2.1.7 on 2019-03-11 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuffsharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('adress_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanProposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data available')),
                ('end_date', models.DateField(verbose_name='Data end return')),
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('pickupAdress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupAdress', to='stuffsharing.Adress')),
                ('returnAdress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returnAdress', to='stuffsharing.Adress')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.Adress')),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='iswillingtorent',
            name='testobject',
        ),
        migrations.RemoveField(
            model_name='iswillingtorent',
            name='testuser',
        ),
        migrations.DeleteModel(
            name='IsWillingToRent',
        ),
        migrations.DeleteModel(
            name='TestObject',
        ),
        migrations.DeleteModel(
            name='TestUser',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.Member'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='original_Proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.LoanProposition'),
        ),
        migrations.AddField(
            model_name='loanproposition',
            name='stuff_for_lown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.Stuff'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.LoanRequest'),
        ),
    ]
