# Generated by Django 2.1.7 on 2019-04-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuffsharing', '0002_remove_profile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='adress',
            new_name='address',
        ),
    ]
