# Generated by Django 2.1.7 on 2019-04-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuffsharing', '0003_auto_20190409_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='Name',
        ),
    ]
