# Generated by Django 2.1.7 on 2019-03-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffsharing', '0003_auto_20190311_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproposition',
            name='tags',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
