# Generated by Django 2.1.7 on 2019-04-04 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stuffsharing', '0004_loanproposition_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.Adress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='adress',
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.Profile'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.Profile'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
