# Generated by Django 2.1.7 on 2019-04-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffsharing', '0004_auto_20190409_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanproposition',
            name='name',
        ),
        migrations.AddField(
            model_name='stuff',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
