# Generated by Django 2.1.7 on 2019-04-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffsharing', '0006_loanproposition_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproposition',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
