# Generated by Django 2.2 on 2019-04-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffsharing', '0007_loanproposition_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanproposition',
            name='tags',
        ),
        migrations.AddField(
            model_name='loanproposition',
            name='bid',
            field=models.BooleanField(default=False),
        ),
    ]
