# Generated by Django 2.1.7 on 2019-04-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffsharing', '0010_auto_20190408_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='adress_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
