# Generated by Django 2.1.7 on 2019-04-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuffsharing', '0014_auto_20190408_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mail',
        ),
    ]
