# Generated by Django 2.1.7 on 2019-04-08 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuffsharing', '0015_remove_profile_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adress',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.Adress'),
        ),
    ]
