# Generated by Django 2.1.7 on 2019-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffsharing', '0016_auto_20190408_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='id',
        ),
        migrations.AlterField(
            model_name='adress',
            name='adress_name',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
