# Generated by Django 2.1.7 on 2019-04-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuffsharing', '0017_auto_20190408_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adress',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
