# Generated by Django 2.1.7 on 2019-04-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuffsharing', '0019_auto_20190408_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.Profile', to_field='user_name'),
        ),
    ]
