# Generated by Django 2.1.7 on 2019-04-08 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuffsharing', '0021_auto_20190409_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproposition',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.Profile', to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuffsharing.Profile', to_field='user_id'),
        ),
    ]
